apiVersion: v2
name: atlas-read
description: Apache Atlas Read Replica for Metadata Management
type: application
version: 1.0.0
appVersion: "3.0.0"  # Will be updated by CI with commit ID
maintainers:
  - name: Atlan Engineering
    email: engineering@atlan.com
keywords:
  - atlas
  - atlas-read
  - metadata
  - read-replica
  - apache-atlas
sources:
  - https://github.com/atlanhq/atlas-metastore
home: https://github.com/atlanhq/atlas-metastore
dependencies:
  - name: cassandra-online-dc
    repository: file://./charts/cassandra-online-dc
    version: 0.x.x  
    condition: _disabled.cassandra_online_dc  # Always false - published separately as OCI
  - name: elasticsearch-read
    repository: file://./charts/elasticsearch-read
    version: 7.x.x
    condition: _disabled.elasticsearch_read  # Always false - published separately as OCI
  - name: elasticsearch-exporter-read
    repository: file://./charts/elasticsearch-exporter-read
    version: 3.3.0
    condition: _disabled.elasticsearch_exporter_read  # Always false - published separately as OCI
