{{- if or .Values.global.esIsolation.enabled .Values.global.globalSvcIsolation.enabled }}
{{- if .Values.rbac.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if eq .Values.rbac.serviceAccountName "" }}
  name: {{ $fullName | quote }}
  namespace: {{ .Values.Namespace }}
  {{- else }}
  name: {{ .Values.rbac.serviceAccountName | quote }}
  namespace: {{ .Values.Namespace }}
  {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $fullName | quote }}
{{- end -}}
{{- end }}
