#!/usr/bin/env bash
# ============================================================================
# setup_local_env.sh — Create deploy/ directory for running Atlas locally
#
# Prerequisites:
#   - Docker services running: docker-compose -f local-dev/docker-compose.yaml up -d
#   - Atlas built: see CLAUDE.md for build commands
#
# Usage:
#   bash dev-support/bulk-purge-test/setup_local_env.sh
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/deploy"

echo "=== Atlas Local Dev Setup ==="
echo "Repo root: $REPO_ROOT"
echo "Deploy dir: $DEPLOY_DIR"
echo ""

# --- 1. Create directory structure ---
echo "[1/5] Creating deploy directories..."
mkdir -p "$DEPLOY_DIR/conf"
mkdir -p "$DEPLOY_DIR/data"
mkdir -p "$DEPLOY_DIR/logs"

# --- 2. Create symlinks to test resources ---
echo "[2/5] Symlinking test resources..."

TEST_DEPLOY="$REPO_ROOT/webapp/src/test/resources/deploy"

for dir in models elasticsearch policies static; do
    target="$TEST_DEPLOY/$dir"
    link="$DEPLOY_DIR/$dir"
    if [ -L "$link" ]; then
        rm "$link"
    elif [ -d "$link" ]; then
        echo "  Removing existing directory $link to replace with symlink"
        rm -rf "$link"
    fi
    if [ -d "$target" ]; then
        ln -s "$target" "$link"
        echo "  $dir -> $target"
    else
        echo "  WARNING: $target does not exist, skipping"
    fi
done

# --- 3. Copy logback config ---
echo "[3/5] Copying logback config..."
LOGBACK_SRC="$REPO_ROOT/local-dev/atlas-logback.xml"
if [ -f "$LOGBACK_SRC" ]; then
    cp "$LOGBACK_SRC" "$DEPLOY_DIR/conf/atlas-logback.xml"
    echo "  Copied atlas-logback.xml"
else
    echo "  WARNING: $LOGBACK_SRC not found"
fi

# --- 4. Copy users-credentials ---
echo "[4/5] Copying users-credentials.properties..."
CREDS_SRC="$TEST_DEPLOY/conf/users-credentials.properties"
if [ -f "$CREDS_SRC" ]; then
    cp "$CREDS_SRC" "$DEPLOY_DIR/conf/users-credentials.properties"
    echo "  Copied users-credentials.properties"
else
    echo "  WARNING: $CREDS_SRC not found"
fi

# --- 5. Generate atlas-application.properties ---
echo "[5/5] Generating atlas-application.properties..."

PROPS_FILE="$DEPLOY_DIR/conf/atlas-application.properties"
cat > "$PROPS_FILE" << 'PROPS'
# ============================================================================
# atlas-application.properties — Generated by setup_local_env.sh
# For local development with Docker services (Cassandra, ES, Redis)
# ============================================================================

# --- Graph storage: Cassandra ---
atlas.graph.storage.backend=cql
atlas.graph.storage.hostname=localhost
atlas.graph.storage.cql.port=9042
atlas.graph.storage.cql.keyspace=atlas_janus
atlas.graph.storage.cql.replication-factor=1
atlas.graph.storage.clustername=atlas-local-cluster
atlas.graph.storage.port=9042
atlas.graph.query.fast-property=true
atlas.graph.query.batch=true
query.batch.properties-mode=all-properties
atlas.use.index.query.to.find.entity.by.unique.attributes=true
atlas.graph.storage.lock.retries=5
atlas.graph.cache.db-cache=false
atlas.graph.storage.write-time=10000

# --- Graph index: Elasticsearch ---
atlas.graph.index.search.backend=elasticsearch
atlas.graph.index.search.hostname=localhost:9200
atlas.graph.index.search.elasticsearch.client-only=true
atlas.graph.index.search.elasticsearch.retry_on_conflict=5
atlas.rebuild.index=true

# --- Notification: External Kafka ---
atlas.notification.embedded=false
atlas.kafka.bootstrap.servers=localhost:9092
atlas.graph.kafka.bootstrap.servers=localhost:9092
atlas.kafka.zookeeper.connect=localhost:2181
atlas.kafka.auto.commit.interval.ms=1000
atlas.kafka.hook.group.id=atlas
atlas.kafka.enable.auto.commit=false
atlas.kafka.auto.offset.reset=earliest
atlas.kafka.session.timeout.ms=30000
atlas.kafka.offsets.topic.replication.factor=1
atlas.kafka.poll.timeout.ms=1000
atlas.notification.create.topics=true
atlas.notification.replicas=1
atlas.notification.topics=ATLAS_HOOK,ATLAS_ENTITIES
atlas.notification.log.failed.messages=true
atlas.notification.consumer.retry.interval=500
atlas.notification.hook.retry.interval=1000

# --- Redis ---
atlas.redis.url=redis://localhost:6379
atlas.redis.sentinel.enabled=false
atlas.redis.sentinel.check_list.enabled=false

# --- Authentication: file-based ---
atlas.authentication.method.file=true
atlas.authentication.method.file.filename=deploy/conf/users-credentials.properties
atlas.authentication.method.kerberos=false
atlas.authentication.method.ldap=false
atlas.authentication.method.ldap.type=none
atlas.authentication.method.keycloak=false
atlas.authentication.method.pam=false
atlas.http.authentication.enabled=false

# --- Security ---
atlas.enableTLS=false
atlas.rest-csrf.enabled=false
atlas.authorizer.impl=none

# --- Server ---
atlas.server.http.port=21000
atlas.server.bind.address=localhost
atlas.rest.address=http://localhost:21000
atlas.server.ha.enabled=false

# --- Delete handler ---
atlas.DeleteHandlerV1.impl=org.apache.atlas.repository.store.graph.v1.SoftDeleteHandlerV1

# --- Entity audit ---
atlas.EntityAuditRepository.impl=org.apache.atlas.repository.audit.NoopEntityAuditRepository
atlas.EntityAuditRepositorySearch.impl=org.apache.atlas.repository.audit.ESBasedAuditRepository

# --- Search ---
atlas.search.fulltext.enable=true
atlas.search.gremlin.enable=false

# --- Lineage ---
atlas.lineage.on.demand.enabled=true

# --- Misc ---
atlas.entity.audit.differential=true
atlas.index.audit.elasticsearch.total_field_limit=2000
atlas.entity.skip.optional.attributes=true

# --- DLQ ---
atlas.kafka.dlq.enabled=false

# --- Index recovery: disabled (monitor thread hangs on shutdown) ---
atlas.index.recovery.enable=false

# --- Config store: DynamicConfigStore (Cassandra-backed) ---
atlas.config.store.cassandra.enabled=true
atlas.config.store.cassandra.activated=true
atlas.config.store.cassandra.consistency.level=LOCAL_ONE
atlas.config.store.cassandra.replication.factor=1
PROPS

echo "  Generated $PROPS_FILE"

echo ""
echo "=== Setup complete ==="
echo ""
echo "Deploy directory structure:"
echo "  deploy/"
echo "  ├── conf/"
echo "  │   ├── atlas-application.properties  (generated)"
echo "  │   ├── atlas-logback.xml             (copied)"
echo "  │   └── users-credentials.properties  (copied)"
echo "  ├── data/"
echo "  ├── logs/"
echo "  ├── models -> webapp/src/test/resources/deploy/models/"
echo "  ├── elasticsearch -> webapp/src/test/resources/deploy/elasticsearch/"
echo "  ├── policies -> webapp/src/test/resources/deploy/policies/"
echo "  └── static -> webapp/src/test/resources/deploy/static/"
echo ""
echo "Next steps:"
echo "  1. Start Docker services:  docker-compose -f local-dev/docker-compose.yaml up -d"
echo "  2. Build Atlas:            see CLAUDE.md for build commands"
echo "  3. Start Atlas:            java -Datlas.home=deploy/ -Datlas.conf=deploy/conf \\"
echo "                               -Datlas.data=deploy/data -Datlas.log.dir=deploy/logs \\"
echo "                               -Dlogback.configurationFile=file:./deploy/conf/atlas-logback.xml \\"
echo "                               --add-opens java.base/java.lang=ALL-UNNAMED -Xms512m \\"
echo "                               org.apache.atlas.Atlas"
echo "  4. Run E2E test:           python3 dev-support/bulk-purge-test/test_bulk_purge.py"
