apiVersion: v2
name: atlas
description: Apache Atlas Metadata Management and Governance Platform
type: application
version: 1.0.0-atlas-ci-cd-updates.8275fa956
appVersion: "8275fa956"
maintainers:
  - name: Atlan Engineering
    email: engineering@atlan.com
keywords:
  - atlas
  - metadata
  - governance
  - data-catalog
  - apache-atlas
sources:
  - https://github.com/atlanhq/atlas-metastore
home: https://github.com/atlanhq/atlas-metastore
dependencies:
  - name: cassandra
    repository: file://./charts/cassandra
    version: 0.x.x
  - name: elasticsearch
    repository: file://./charts/elasticsearch
    version: 7.x.x
  - name: logstash
    repository: file://./charts/logstash
    version: 9.x.x
