{{- if or .Values.global.esIsolation.enabled .Values.global.globalSvcIsolation.enabled }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch-exporter.fullname" . }}
  namespace: {{ .Values.Namespace }}
  labels:
    chart: {{ template "elasticsearch-exporter.chart" . }}
    app: {{ template "elasticsearch-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
{{- end }}
